//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApplication_DB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistartionMaster
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Emailid { get; set; }
        public string Gender { get; set; }
        public Nullable<long> Mobno { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
